-- KWhyzor Supabase Database Migration
-- ============================================================================
-- CRITICAL: Run this entire SQL script in your Supabase Project > SQL Editor
-- https://gnxiqzffkarsfrncpwgi.supabase.co
-- ============================================================================
--
-- This migration creates all missing tables, functions, triggers, and storage
-- buckets required by the KWhyzor application.
--
-- SAFE TO RUN MULTIPLE TIMES: All statements use IF NOT EXISTS / DROP IF EXISTS
-- EXISTING DATA IS PRESERVED: No tables are dropped or truncated
--
-- ============================================================================

-- ============================================================================
-- 1. CORE TABLES
-- ============================================================================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  display_name text,
  avatar_url text,
  phone text,
  location text,
  role text not null default 'user' check (role in ('user','super_admin')),
  plan text not null default 'Free' check (plan in ('Free','Pro','Business')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists display_name text;
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists phone text;
alter table public.profiles add column if not exists location text;
alter table public.profiles add column if not exists role text default 'user';
alter table public.profiles add column if not exists plan text not null default 'Free';
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create table if not exists public.appliances (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  category text,
  wattage numeric(10,2) not null check (wattage >= 0),
  quantity int not null default 1 check (quantity > 0),
  hours_per_day numeric(5,2) not null default 0 check (hours_per_day >= 0),
  days_per_month int not null default 30 check (days_per_month > 0),
  created_at timestamptz not null default now()
);

-- ============================================================================
-- 2. BILL DOCUMENTS & OCR PIPELINE
-- ============================================================================

create table if not exists public.bill_documents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_path text not null unique,
  original_filename text not null,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes > 0),
  processing_status text not null check (processing_status in ('processing','not_configured','ocr_failed','review_required','rejected','verified')),
  created_at timestamptz not null default now()
);

alter table public.bill_documents drop constraint if exists bill_documents_processing_status_check;
alter table public.bill_documents add constraint bill_documents_processing_status_check check (processing_status in ('processing','not_configured','ocr_failed','review_required','rejected','verified'));

create table if not exists public.bill_extractions (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null unique references public.bill_documents(id) on delete cascade,
  raw_ocr_text text,
  provider_evidence text,
  extraction_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- ============================================================================
-- 3. ELECTRICITY BILLS
-- ============================================================================

create table if not exists public.electricity_bills (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  document_id uuid references public.bill_documents(id) on delete set null,
  provider text,
  consumer_number text,
  meter_number text,
  bill_number text,
  bill_date date,
  due_date date,
  billing_period_start date,

-- ============================================================================
-- 4. BILL FIELD VALUES, METER READINGS, VERIFICATION EVENTS
-- ============================================================================

create table if not exists public.bill_field_values (
  id uuid primary key default gen_random_uuid(),
  bill_id uuid not null references public.electricity_bills(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  field_name text not null,
  value_text text,
  value_numeric numeric,
  source text not null default 'USER_PROVIDED',
  confidence text not null default 'user-confirmed',
  evidence text,
  created_at timestamptz not null default now()
);

create table if not exists public.meter_readings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  meter_number text,
  previous_reading numeric(12,3),
  current_reading numeric(12,3),
  multiplier numeric(10,4),
  reading_date date,
  reading_status text not null default 'UNKNOWN' check (reading_status in ('ACTUAL','ESTIMATED','PROVISIONAL','UNKNOWN')),
  calculated_consumption_kwh numeric(12,3),
  created_at timestamptz not null default now()
);

create table if not exists public.bill_verification_events (
  id uuid primary key default gen_random_uuid(),
  bill_id uuid not null references public.electricity_bills(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  event_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.bill_charges (
  id uuid primary key default gen_random_uuid(),
  bill_id uuid not null references public.electricity_bills(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  charge_name text not null,
  amount numeric(12,2) not null,
  created_at timestamptz not null default now()
);


-- ============================================================================
-- 5. ELECTRICITY TWIN, SIMULATIONS, EV DATA, SOLAR DATA
-- ============================================================================

create table if not exists public.electricity_twin_data (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  appliance_name text not null,
  wattage numeric(10,2),
  quantity int not null default 1,
  hours_per_day numeric(5,2),
  days_per_month int not null default 30,
  source text not null default 'USER_ESTIMATE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.simulations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  scenario jsonb not null default '{}'::jsonb,
  results jsonb not null default '{}'::jsonb,
  source text not null default 'USER_ESTIMATE',
  created_at timestamptz not null default now()
);

create table if not exists public.ev_data (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  source text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.solar_data (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,

-- ============================================================================
-- 6. SUBSCRIPTIONS, PLANS, PAYMENTS
-- ============================================================================

create table if not exists public.plans (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  amount numeric(12,2) not null,
  currency text not null default 'INR',
  interval text not null default 'monthly',
  features jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  plan text not null,
  status text not null default 'inactive' check (status in ('active','inactive','cancelled','past_due')),
  gateway text,
  gateway_subscription_id text,
  current_period_start timestamptz,
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  order_id text not null unique,
  payment_id text,
  gateway text not null default 'razorpay',
  amount numeric(12,2) not null,
  currency text not null default 'INR',
  status text not null default 'created' check (status in ('created','paid','failed','refunded')),
  webhook_verified boolean not null default false,
  provider_response jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_events (
  id uuid primary key default gen_random_uuid(),
  payment_id uuid references public.payments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider_event_id text unique,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
  source text not null,

-- ============================================================================
-- 7. NOTIFICATIONS, AUDIT LOGS, ENERGY DATA, REPORTS
-- ============================================================================

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  notification_type text not null,
  status text not null default 'pending',
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  action text not null,
  resource_type text,
  resource_id text,
  metadata jsonb not null default '{}'::jsonb,
  ip_address text,
  created_at timestamptz not null default now()
);

create table if not exists public.energy_data (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  reading_date date not null,
  units_kwh numeric(12,3),
  amount numeric(12,2),
  source text not null default 'USER_PROVIDED',
  created_at timestamptz not null default now()
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  report_type text not null,
  period_start date,
  period_end date,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.report_items (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references public.reports(id) on delete cascade,

-- ============================================================================
-- 8. FUNCTIONS & TRIGGERS
-- ============================================================================

create or replace function public.get_super_admin_email()
returns text
language sql
stable
as $$
  select coalesce(
    nullif(current_setting('app.settings.super_admin_email', true), ''),
    null::text
  );
$$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
declare
  super_admin_email text;
begin
  super_admin_email := get_super_admin_email();
  if super_admin_email is not null and lower(new.email) = lower(super_admin_email) then
    insert into public.profiles(id, full_name, role)
    values(new.id, coalesce(new.raw_user_meta_data->>'full_name', ''), 'super_admin')
    on conflict(id) do nothing;
  else
    insert into public.profiles(id, full_name, role)
    values(new.id, coalesce(new.raw_user_meta_data->>'full_name', ''), 'user')
    on conflict(id) do nothing;
  end if;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.protect_profile_system_fields()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.role is distinct from old.role then
    raise exception 'The profile role cannot be changed directly';
  end if;
  if new.plan is distinct from old.plan then
    raise exception 'The profile plan cannot be changed directly';
  end if;
  return new;
end; $$;

drop trigger if exists protect_profile_system_fields on public.profiles;
create trigger protect_profile_system_fields before update on public.profiles
for each row execute procedure public.protect_profile_system_fields();

create or replace function public.get_admin_analytics()
returns json language plpgsql security definer set search_path=public as $$
declare
  result json;

-- ============================================================================
-- 9. ROW LEVEL SECURITY (RLS) - Enable RLS
-- ============================================================================

alter table public.profiles enable row level security;
alter table public.appliances enable row level security;
alter table public.electricity_providers enable row level security;
alter table public.bill_documents enable row level security;
alter table public.bill_extractions enable row level security;
alter table public.electricity_bills enable row level security;
alter table public.bill_field_values enable row level security;
alter table public.meter_readings enable row level security;
alter table public.bill_verification_events enable row level security;
alter table public.bill_charges enable row level security;
alter table public.bill_comparisons enable row level security;
alter table public.electricity_twin_data enable row level security;
alter table public.simulations enable row level security;
alter table public.ev_data enable row level security;
alter table public.solar_data enable row level security;
alter table public.subscriptions enable row level security;
alter table public.plans enable row level security;
alter table public.payments enable row level security;
alter table public.payment_events enable row level security;
alter table public.notifications enable row level security;
alter table public.audit_logs enable row level security;
alter table public.energy_data enable row level security;

-- ============================================================================
-- 10. RLS POLICIES (Part 1: Core tables)
-- ============================================================================

drop policy if exists "profiles own rows" on public.profiles;
create policy "profiles own rows" on public.profiles for all to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "appliances own rows" on public.appliances;
create policy "appliances own rows" on public.appliances for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "providers public read" on public.electricity_providers;
create policy "providers public read" on public.electricity_providers for select to authenticated using (true);

drop policy if exists "bill documents own rows" on public.bill_documents;
create policy "bill documents own rows" on public.bill_documents for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "bill extractions own rows" on public.bill_extractions;
create policy "bill extractions own rows" on public.bill_extractions for all to authenticated using (exists (select 1 from public.bill_documents d where d.id = document_id and d.user_id = auth.uid())) with check (exists (select 1 from public.bill_documents d where d.id = document_id and d.user_id = auth.uid()));

drop policy if exists "electricity bills own rows" on public.electricity_bills;
create policy "electricity bills own rows" on public.electricity_bills for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "bill field values own rows" on public.bill_field_values;
create policy "bill field values own rows" on public.bill_field_values for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "meter readings own rows" on public.meter_readings;

-- ============================================================================
-- 11. RLS POLICIES (Part 2: Bill analysis tables)
-- ============================================================================

drop policy if exists "bill verification events own rows" on public.bill_verification_events;
create policy "bill verification events own rows" on public.bill_verification_events for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "bill charges own rows" on public.bill_charges;
create policy "bill charges own rows" on public.bill_charges for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "bill comparisons own rows" on public.bill_comparisons;
create policy "bill comparisons own rows" on public.bill_comparisons for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "electricity twin data own rows" on public.electricity_twin_data;
create policy "electricity twin data own rows" on public.electricity_twin_data for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "simulations own rows" on public.simulations;
create policy "simulations own rows" on public.simulations for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "ev data own rows" on public.ev_data;
create policy "ev data own rows" on public.ev_data for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "solar data own rows" on public.solar_data;

-- ============================================================================
-- 12. RLS POLICIES (Part 3: Subscriptions, payments, notifications)
-- ============================================================================

drop policy if exists "subscriptions own rows" on public.subscriptions;
create policy "subscriptions own rows" on public.subscriptions for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "plans public read" on public.plans;
create policy "plans public read" on public.plans for select to authenticated using (active = true);

drop policy if exists "payments own rows" on public.payments;
create policy "payments own rows" on public.payments for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "payment events own rows" on public.payment_events;
create policy "payment events own rows" on public.payment_events for select to authenticated using (auth.uid() = user_id);

drop policy if exists "notifications own rows" on public.notifications;
create policy "notifications own rows" on public.notifications for select to authenticated using (auth.uid() = user_id);

drop policy if exists "energy data own rows" on public.energy_data;
create policy "energy data own rows" on public.energy_data for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "reports own rows" on public.reports;
create policy "reports own rows" on public.reports for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);


-- ============================================================================
-- 13. STORAGE BUCKETS
-- ============================================================================

insert into storage.buckets (id, name, public) values ('electricity-bills', 'electricity-bills', false) on conflict (id) do nothing;

drop policy if exists "electricity bills owner read" on storage.objects;
create policy "electricity bills owner read" on storage.objects for select to authenticated using (bucket_id = 'electricity-bills' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "electricity bills owner upload" on storage.objects;
create policy "electricity bills owner upload" on storage.objects for insert to authenticated with check (bucket_id = 'electricity-bills' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "electricity bills owner delete" on storage.objects;
create policy "electricity bills owner delete" on storage.objects for delete to authenticated using (bucket_id = 'electricity-bills' and (storage.foldername(name))[1] = auth.uid()::text);

-- ============================================================================
-- 14. INDEXES
-- ============================================================================

create index if not exists appliances_user_id_idx on public.appliances(user_id);
create index if not exists bill_documents_user_id_idx on public.bill_documents(user_id);
create index if not exists bill_extractions_document_id_idx on public.bill_extractions(document_id);
create index if not exists electricity_bills_user_id_idx on public.electricity_bills(user_id);
create index if not exists electricity_bills_verification_status_idx on public.electricity_bills(verification_status);
create index if not exists bill_field_values_bill_id_idx on public.bill_field_values(bill_id);
create index if not exists bill_verification_events_bill_id_idx on public.bill_verification_events(bill_id);
create index if not exists meter_readings_user_id_idx on public.meter_readings(user_id);
create index if not exists subscriptions_user_id_idx on public.subscriptions(user_id);
create index if not exists payments_user_id_idx on public.payments(user_id);
create index if not exists payments_order_id_idx on public.payments(order_id);
create index if not exists notifications_user_id_idx on public.notifications(user_id);
create index if not exists energy_data_user_id_idx on public.energy_data(user_id);
create index if not exists reports_user_id_idx on public.reports(user_id);

-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================
-- After running this migration:
-- 1. Set the super admin email: SELECT set_config('app.settings.super_admin_email', 'your-email@example.com', false);
-- 2. Enable email auth in Supabase Dashboard > Authentication > Providers > Email
-- 3. Test by signing up with the owner email - it should get super_admin role
-- ============================================================================
