-- RushXArena Supabase Database Schema
-- ============================================================================
-- SETUP INSTRUCTIONS (MUST READ)
-- ============================================================================
-- 
-- 1. Run this entire SQL script in your Supabase Project > SQL Editor
--    Copy and paste the entire file, then execute
--
-- 2. CRITICAL: Configure the Super Admin Email
--    After running this script, manually update the super_admin_email in the trigger:
--    
--    Replace 'ayushkmr802210@gmail.com' with the actual owner's email address
--    in the get_super_admin_email() function definition (search for "ayushkmr802210@gmail.com")
--
--    Alternative: Set it as a database configuration:
--    Run this command in SQL Editor with your actual email:
--    
--      SELECT set_config('app.settings.super_admin_email', 'owner@example.com', false);
--    
--    Then update the handle_new_user function to read from that setting.
--
-- 3. Enable Email Authentication in Supabase Dashboard:
--    Authentication > Providers > Email
--
-- 4. Set appropriate RLS Policies (already included in this script)
--
-- 5. Test the setup by creating a new account with the owner email
--    It should automatically receive 'super_admin' role
--
-- ============================================================================

create extension if not exists pgcrypto;

create or replace function public.get_super_admin_email()
returns text
language sql
stable
as $$
  select coalesce(
    nullif(current_setting('app.settings.super_admin_email', true), ''),
    null::text
  );
$$;

-- Optional override for production use:
-- select set_config('app.settings.super_admin_email', 'owner@example.com', false);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  display_name text,
  avatar_url text,
  phone text,
  location text,
  role text not null default 'user' check (role in ('user','super_admin')),
  plan text not null default 'Free' check (plan in ('Free','Pro','Business')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists display_name text;
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists phone text;
alter table public.profiles add column if not exists location text;
alter table public.profiles add column if not exists role text default 'user';
alter table public.profiles add column if not exists plan text not null default 'Free';
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create table if not exists public.bills (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  billing_date date not null default current_date,
  amount numeric(12,2) not null check (amount >= 0),
  units_kwh numeric(12,3) not null check (units_kwh >= 0),
  previous_units_kwh numeric(12,3),
  ocr_status text default 'manual',
  created_at timestamptz not null default now()
);

create table if not exists public.appliances (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  category text,
  wattage numeric(10,2) not null check (wattage >= 0),
  quantity integer not null default 1 check (quantity > 0),
  hours_per_day numeric(5,2) not null default 1 check (hours_per_day between 0 and 24),
  days_per_month integer not null default 30 check (days_per_month between 1 and 31),
  created_at timestamptz not null default now()
);

create table if not exists public.energy_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text, energy_score integer check (energy_score between 0 and 100),
  estimated_consumption_kwh numeric(12,3), estimated_cost numeric(12,2),
  saving_opportunity numeric(12,2), ai_summary text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.bills enable row level security;
alter table public.appliances enable row level security;
alter table public.energy_reports enable row level security;

-- Profiles: Users can only view and edit their own profile
-- CRITICAL: Users cannot modify the 'role' field - it can only be set by the database trigger or admin functions
drop policy if exists "profiles own rows" on public.profiles;
create policy "profiles own rows" on public.profiles for select using (auth.uid()=id);

-- Users can update only specific allowed columns (NOT role, plan, or system fields)
drop policy if exists "profiles update own data" on public.profiles;
create policy "profiles update own data" on public.profiles for update 
  using (auth.uid()=id) 
  with check (auth.uid()=id);

-- Users cannot insert new profiles directly
drop policy if exists "profiles no direct insert" on public.profiles;
create policy "profiles no direct insert" on public.profiles for insert with check (false);

drop policy if exists "bills own rows" on public.bills;
create policy "bills own rows" on public.bills for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "appliances own rows" on public.appliances;
create policy "appliances own rows" on public.appliances for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "reports own rows" on public.energy_reports;
create policy "reports own rows" on public.energy_reports for all using (auth.uid()=user_id) with check (auth.uid()=user_id);

-- Private avatar storage. Upload paths must start with the authenticated user's id.
insert into storage.buckets (id, name, public) values ('avatars', 'avatars', false) on conflict (id) do nothing;
drop policy if exists "avatar owner read" on storage.objects;
create policy "avatar owner read" on storage.objects for select to authenticated using (bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists "avatar owner upload" on storage.objects;
create policy "avatar owner upload" on storage.objects for insert to authenticated with check (bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists "avatar owner update" on storage.objects;
create policy "avatar owner update" on storage.objects for update to authenticated using (bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text) with check (bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists "avatar owner delete" on storage.objects;
create policy "avatar owner delete" on storage.objects for delete to authenticated using (bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
declare
  super_admin_email text;
begin
  -- Get the configured super admin email from the configuration function
  super_admin_email := get_super_admin_email();
  
  -- Assign super_admin role only to the explicitly configured owner email
  -- This is the ONLY way a user can become super_admin
  if super_admin_email is not null and lower(new.email) = lower(super_admin_email) then
    insert into public.profiles(id, full_name, role)
    values(new.id, coalesce(new.raw_user_meta_data->>'full_name', ''), 'super_admin')
    on conflict(id) do nothing;
  else
    -- All other users get the 'user' role
    insert into public.profiles(id, full_name, role)
    values(new.id, coalesce(new.raw_user_meta_data->>'full_name', ''), 'user')
    on conflict(id) do nothing;
  end if;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Prevent clients from changing authorization and subscription fields directly.
create or replace function public.protect_profile_system_fields()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.role is distinct from old.role then
    raise exception 'The profile role cannot be changed directly';
  end if;
  if new.plan is distinct from old.plan then
    raise exception 'The profile plan cannot be changed directly';
  end if;
  return new;
end; $$;

drop trigger if exists protect_profile_system_fields on public.profiles;
create trigger protect_profile_system_fields before update on public.profiles
for each row execute procedure public.protect_profile_system_fields();

-- Admin Dashboard: Secure RPC function to get platform analytics
-- Only accessible to users with 'super_admin' role
create or replace function public.get_admin_analytics()
returns json language plpgsql security definer set search_path=public as $$
declare
  result json;
begin
  -- Verify that the calling user is a super admin
  if (select role from public.profiles where id = auth.uid()) != 'super_admin' then
    raise exception 'Unauthorized: Admin access required';
  end if;

  -- Return analytics data (safe to expose publicly available statistics)
  select json_build_object(
    'total_users', (select count(*) from public.profiles),
    'total_super_admins', (select count(*) from public.profiles where role = 'super_admin'),
    'total_bills', (select count(*) from public.bills),
    'total_simulations', (select count(*) from public.energy_reports),
    'users_created_this_month', (select count(*) from public.profiles where created_at >= date_trunc('month', now())),
    'active_plans', json_build_object(
      'free', (select count(*) from public.profiles where plan = 'Free'),
      'pro', (select count(*) from public.profiles where plan = 'Pro'),
      'business', (select count(*) from public.profiles where plan = 'Business')
    )
  ) into result;
  
  return result;
end; $$;

-- Admin Dashboard: Get paginated user list (safe non-sensitive fields only)
create or replace function public.get_admin_users(limit_count int default 20, offset_count int default 0)
returns table(id uuid, full_name text, email text, plan text, role text, created_at timestamptz) 
language plpgsql security definer set search_path=public as $$
begin
  -- Verify that the calling user is a super admin
  if (select role from public.profiles where id = auth.uid()) != 'super_admin' then
    raise exception 'Unauthorized: Admin access required';
  end if;

  -- Return user list with non-sensitive fields
  return query
  select 
    p.id, 
    p.full_name, 
    u.email, 
    p.plan, 
    p.role, 
    p.created_at
  from public.profiles p
  join auth.users u on u.id = p.id
  order by p.created_at desc
  limit limit_count
  offset offset_count;
end; $$;

-- Additional relational tables for the Electricity Twin and energy scenarios.
create table if not exists public.homes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default 'My Home',
  address text,
  city text,
  state text,
  country text not null default 'India',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  home_id uuid not null references public.homes(id) on delete cascade,
  name text not null,
  room_type text,
  created_at timestamptz not null default now()
);

create table if not exists public.bill_investigations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  bill_id bigint references public.bills(id) on delete set null,
  likely_cause text,
  confidence text check (confidence in ('low', 'medium', 'high')),
  analysis_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.ev_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  home_id uuid references public.homes(id) on delete cascade,
  vehicle_name text,
  battery_capacity_kwh numeric check (battery_capacity_kwh >= 0),
  daily_distance_km numeric check (daily_distance_km >= 0),
  efficiency_kwh_per_km numeric check (efficiency_kwh_per_km >= 0),
  charging_efficiency numeric not null default 0.90 check (charging_efficiency > 0 and charging_efficiency <= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.solar_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  home_id uuid references public.homes(id) on delete cascade,
  system_size_kw numeric check (system_size_kw >= 0),
  average_daily_generation_kwh numeric check (average_daily_generation_kwh >= 0),
  net_metering_enabled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.energy_simulations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  home_id uuid references public.homes(id) on delete cascade,
  name text not null,
  scenario_type text,
  input_data jsonb not null default '{}'::jsonb,
  estimated_consumption_kwh numeric check (estimated_consumption_kwh >= 0),
  estimated_bill_amount numeric check (estimated_bill_amount >= 0),
  assumptions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Add updated timestamps to existing tables when this schema is applied to an older project.
alter table public.homes add column if not exists updated_at timestamptz not null default now();
alter table public.ev_profiles add column if not exists updated_at timestamptz not null default now();
alter table public.solar_profiles add column if not exists updated_at timestamptz not null default now();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists homes_updated_at on public.homes;
create trigger homes_updated_at before update on public.homes
for each row execute procedure public.set_updated_at();
drop trigger if exists ev_profiles_updated_at on public.ev_profiles;
create trigger ev_profiles_updated_at before update on public.ev_profiles
for each row execute procedure public.set_updated_at();
drop trigger if exists solar_profiles_updated_at on public.solar_profiles;
create trigger solar_profiles_updated_at before update on public.solar_profiles
for each row execute procedure public.set_updated_at();

-- Ownership policies for all additional user-owned tables.
alter table public.homes enable row level security;
alter table public.rooms enable row level security;
alter table public.bill_investigations enable row level security;
alter table public.ev_profiles enable row level security;
alter table public.solar_profiles enable row level security;
alter table public.energy_simulations enable row level security;

drop policy if exists "homes own rows" on public.homes;
create policy "homes own rows" on public.homes for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "rooms in own homes" on public.rooms;
create policy "rooms in own homes" on public.rooms for all to authenticated
using (exists (select 1 from public.homes where homes.id = rooms.home_id and homes.user_id = auth.uid()))
with check (exists (select 1 from public.homes where homes.id = rooms.home_id and homes.user_id = auth.uid()));

drop policy if exists "investigations own rows" on public.bill_investigations;
create policy "investigations own rows" on public.bill_investigations for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "ev profiles own rows" on public.ev_profiles;
create policy "ev profiles own rows" on public.ev_profiles for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "solar profiles own rows" on public.solar_profiles;
create policy "solar profiles own rows" on public.solar_profiles for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "simulations own rows" on public.energy_simulations;
create policy "simulations own rows" on public.energy_simulations for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Private storage for bills and generated reports. Paths must begin with the authenticated user ID.
insert into storage.buckets (id, name, public) values ('bills', 'bills', false) on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('reports', 'reports', false) on conflict (id) do nothing;

drop policy if exists "bill files owner read" on storage.objects;
create policy "bill files owner read" on storage.objects for select to authenticated
using (bucket_id = 'bills' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "bill files owner upload" on storage.objects;
create policy "bill files owner upload" on storage.objects for insert to authenticated
with check (bucket_id = 'bills' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "bill files owner delete" on storage.objects;
create policy "bill files owner delete" on storage.objects for delete to authenticated
using (bucket_id = 'bills' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "report files owner read" on storage.objects;
create policy "report files owner read" on storage.objects for select to authenticated
using (bucket_id = 'reports' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "report files owner upload" on storage.objects;
create policy "report files owner upload" on storage.objects for insert to authenticated
with check (bucket_id = 'reports' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "report files owner delete" on storage.objects;
create policy "report files owner delete" on storage.objects for delete to authenticated
using (bucket_id = 'reports' and (storage.foldername(name))[1] = auth.uid()::text);

create index if not exists homes_user_id_idx on public.homes(user_id);
create index if not exists rooms_home_id_idx on public.rooms(home_id);
create index if not exists investigations_user_id_idx on public.bill_investigations(user_id);
create index if not exists ev_profiles_user_id_idx on public.ev_profiles(user_id);
create index if not exists solar_profiles_user_id_idx on public.solar_profiles(user_id);
create index if not exists simulations_user_id_idx on public.energy_simulations(user_id);

-- Verified bill pipeline. Raw documents and OCR are kept separate from user-confirmed data.
create table if not exists public.bill_documents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_path text not null unique,
  original_filename text not null,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes > 0),
  processing_status text not null check (processing_status in ('processing','not_configured','ocr_failed','review_required','rejected','verified')),
  created_at timestamptz not null default now()
);
alter table public.bill_documents drop constraint if exists bill_documents_processing_status_check;
alter table public.bill_documents add constraint bill_documents_processing_status_check check (processing_status in ('processing','not_configured','ocr_failed','review_required','rejected','verified'));

create table if not exists public.bill_extractions (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null unique references public.bill_documents(id) on delete cascade,
  raw_ocr_text text,
  provider_evidence text,
  extraction_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.electricity_bills (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  document_id uuid references public.bill_documents(id) on delete set null,
  provider text,
  consumer_number text,
  meter_number text,
  bill_number text,
  bill_date date,
  due_date date,
  billing_period_start date,
  billing_period_end date,
  units_kwh numeric(12,3),
  total_payable numeric(12,2),
  verification_status text not null check (verification_status in ('review_required','verified')),
  created_at timestamptz not null default now(),
  verified_at timestamptz
);

alter table public.bill_documents enable row level security;
alter table public.bill_extractions enable row level security;
alter table public.electricity_bills enable row level security;
drop policy if exists "bill documents own rows" on public.bill_documents;
create policy "bill documents own rows" on public.bill_documents for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "bill extractions own rows" on public.bill_extractions;
create policy "bill extractions own rows" on public.bill_extractions for all to authenticated using (exists (select 1 from public.bill_documents d where d.id = document_id and d.user_id = auth.uid())) with check (exists (select 1 from public.bill_documents d where d.id = document_id and d.user_id = auth.uid()));
drop policy if exists "electricity bills own rows" on public.electricity_bills;
create policy "electricity bills own rows" on public.electricity_bills for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public) values ('electricity-bills', 'electricity-bills', false) on conflict (id) do nothing;
drop policy if exists "electricity bills owner read" on storage.objects;
create policy "electricity bills owner read" on storage.objects for select to authenticated using (bucket_id = 'electricity-bills' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "electricity bills owner upload" on storage.objects;
create policy "electricity bills owner upload" on storage.objects for insert to authenticated with check (bucket_id = 'electricity-bills' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "electricity bills owner delete" on storage.objects;
create policy "electricity bills owner delete" on storage.objects for delete to authenticated using (bucket_id = 'electricity-bills' and (storage.foldername(name))[1] = auth.uid()::text);

create table if not exists public.meter_readings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  meter_number text,
  previous_reading numeric(12,3),
  current_reading numeric(12,3),
  multiplier numeric(12,3),
  reading_date date,
  reading_status text not null default 'UNKNOWN' check (reading_status in ('ACTUAL','ESTIMATED','PROVISIONAL','UNKNOWN')),
  calculated_consumption_kwh numeric(12,3),
  created_at timestamptz not null default now()
);

alter table public.meter_readings enable row level security;
drop policy if exists "meter readings own rows" on public.meter_readings;
create policy "meter readings own rows" on public.meter_readings for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table if not exists public.bill_field_values (
  id uuid primary key default gen_random_uuid(),
  bill_id uuid not null references public.electricity_bills(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  field_name text not null,
  value_text text,
  value_numeric numeric,
  source text not null check (source in ('ACTUAL_FROM_BILL','USER_PROVIDED','CALCULATED_BY_RUSHXARENA','USER_ESTIMATE','OCR_UNVERIFIED','NOT_AVAILABLE')),
  confidence text,
  evidence text,
  created_at timestamptz not null default now()
);

create table if not exists public.bill_verification_events (
  id uuid primary key default gen_random_uuid(),
  bill_id uuid not null references public.electricity_bills(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in ('uploaded','processed','reviewed','corrected','verified','rejected')),
  event_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.bill_field_values enable row level security;
alter table public.bill_verification_events enable row level security;
drop policy if exists "bill fields own rows" on public.bill_field_values;
create policy "bill fields own rows" on public.bill_field_values for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "bill verification events own rows" on public.bill_verification_events;
create policy "bill verification events own rows" on public.bill_verification_events for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  order_id text unique,
  payment_id text unique,
  gateway text not null,
  amount numeric(12,2) not null check (amount >= 0),
  currency text not null default 'INR',
  payment_method text,
  provider_response jsonb,
  status text not null check (status in ('created','pending','paid','failed','refunded')),
  webhook_verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.payments add column if not exists payment_method text;
alter table public.payments add column if not exists provider_response jsonb;

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  plan text not null,
  status text not null check (status in ('active','inactive','past_due','cancelled')),
  gateway text,
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists subscriptions_user_id_unique on public.subscriptions(user_id);

alter table public.payments enable row level security;
alter table public.subscriptions enable row level security;
drop policy if exists "payments own rows" on public.payments;
create policy "payments own rows" on public.payments for select to authenticated using (auth.uid() = user_id);
drop policy if exists "subscriptions own rows" on public.subscriptions;
create policy "subscriptions own rows" on public.subscriptions for select to authenticated using (auth.uid() = user_id);

create table if not exists public.bill_comparisons (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  first_bill_id uuid not null references public.electricity_bills(id) on delete cascade,
  second_bill_id uuid not null references public.electricity_bills(id) on delete cascade,
  comparison_data jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.electricity_providers (
  id uuid primary key default gen_random_uuid(), name text not null unique, code text unique, created_at timestamptz not null default now()
);
create table if not exists public.electricity_twin_data (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  home_id uuid references public.homes(id) on delete cascade, data jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  report_type text not null, source_bill_ids uuid[] not null default '{}', report_data jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete set null,
  action text not null, entity_type text, entity_id text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
alter table public.bill_comparisons enable row level security;
alter table public.electricity_twin_data enable row level security;
alter table public.reports enable row level security;
alter table public.audit_logs enable row level security;
drop policy if exists "bill comparisons own rows" on public.bill_comparisons;
create policy "bill comparisons own rows" on public.bill_comparisons for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "twin data own rows" on public.electricity_twin_data;
create policy "twin data own rows" on public.electricity_twin_data for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "reports own rows" on public.reports;
create policy "reports own rows" on public.reports for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "audit logs own rows" on public.audit_logs;
create policy "audit logs own rows" on public.audit_logs for select to authenticated using (auth.uid() = user_id);

create table if not exists public.bill_charges (
  id uuid primary key default gen_random_uuid(), bill_id uuid not null references public.electricity_bills(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade, charge_type text not null, amount numeric(12,2), source text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.energy_data (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, meter_id text,
  source text not null, reading_at timestamptz, current_reading numeric(12,3), previous_reading numeric(12,3), consumption numeric(12,3), unit text not null default 'kWh', tariff numeric(12,4), cost numeric(12,2), status text not null, source_reference text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.plans (
  id uuid primary key default gen_random_uuid(), name text not null unique, amount numeric(12,2) not null, currency text not null default 'INR', active boolean not null default true, created_at timestamptz not null default now()
);
create table if not exists public.payment_events (
  id uuid primary key default gen_random_uuid(), payment_id uuid references public.payments(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, provider_event_id text unique, event_type text not null, payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.report_items (
  id uuid primary key default gen_random_uuid(), report_id uuid not null references public.reports(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, label text not null, value_text text, source text, created_at timestamptz not null default now()
);
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, notification_type text not null, status text not null default 'pending', data jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.ev_data (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, data jsonb not null default '{}'::jsonb, source text not null, created_at timestamptz not null default now()
);
create table if not exists public.solar_data (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, data jsonb not null default '{}'::jsonb, source text not null, created_at timestamptz not null default now()
);
alter table public.bill_charges enable row level security; alter table public.energy_data enable row level security; alter table public.plans enable row level security; alter table public.payment_events enable row level security; alter table public.report_items enable row level security; alter table public.notifications enable row level security; alter table public.ev_data enable row level security; alter table public.solar_data enable row level security;
drop policy if exists "bill charges own rows" on public.bill_charges; create policy "bill charges own rows" on public.bill_charges for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "energy data own rows" on public.energy_data; create policy "energy data own rows" on public.energy_data for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "plans public read" on public.plans; create policy "plans public read" on public.plans for select to authenticated using (active = true);
drop policy if exists "payment events own rows" on public.payment_events; create policy "payment events own rows" on public.payment_events for select to authenticated using (auth.uid() = user_id);
drop policy if exists "report items own rows" on public.report_items; create policy "report items own rows" on public.report_items for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "notifications own rows" on public.notifications; create policy "notifications own rows" on public.notifications for select to authenticated using (auth.uid() = user_id);
drop policy if exists "ev data own rows" on public.ev_data; create policy "ev data own rows" on public.ev_data for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "solar data own rows" on public.solar_data; create policy "solar data own rows" on public.solar_data for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
